// Traductions anglaises de l'interface : texte français → texte anglais.
// Les {0}, {1}… sont remplacés par les valeurs passées à T().
window.BERNARD_EN = {
  "élément non inclus": "item not included",
  "éléments non inclus": "items not included",
  "fichier spécial ignoré": "special file skipped",
  "fichiers spéciaux ignorés": "special files skipped",
  " (tubes, sockets)": " (pipes, sockets)",
  "Bernard — assistant de migration": "Bernard — migration assistant",
  "Étapes": "Steps",
  "Bienvenue": "Welcome",
  "Démarrage…": "Starting…",
  "Revenir": "Back",
  "ce mois-ci": "this month",
  "{0} mois": "{0} months",
  "1 mois": "1 month",
  "il y a {0}": "{0} ago",
  "{0} ans": "{0} years",
  "1 an": "1 year",
  "il y a {0} et {1}": "{0} and {1} ago",
  "moins de 2 min": "under 2 min",
  "{0} h {1}": "{0} h {1} min",
  "Erreur inattendue": "Unexpected error",
  "Source": "Source",
  "Connexion": "Connection",
  "Analyse": "Analysis",
  "Choix": "Choices",
  "Migration": "Migration",
  "Bilan": "Summary",
  "Rien n'est jamais modifié sur l'ancien ordinateur.": "Nothing is ever changed on the old computer.",
  "Rôle": "Role",
  "Destination": "Destination",
  "Envoi": "Sending",
  "Terminé": "Done",
  "Rien n'est modifié sur cet ordinateur : ses données sont seulement lues.": "Nothing is changed on this computer: its data is only read.",
  "Lancez Bernard sur les deux ordinateurs, dans l'ordre que vous voulez.": "Open Bernard on both computers, in whichever order you like.",
  "Préparation": "Getting ready",
  "Bernard fait l'inventaire de cet ordinateur. Rien n'est modifié.": "Bernard is taking stock of this computer. Nothing is changed.",
  "Le nouvel ordinateur analyse vos données": "The new computer is looking at your data",
  "Il prépare la liste de ce qui peut être transféré.": "It is preparing the list of what can be transferred.",
  "Faites votre choix sur le nouvel ordinateur": "Make your choices on the new computer",
  "Cochez sur le nouvel ordinateur ce qui vient avec vous, puis lancez la migration. Cet ordinateur attend.": "On the new computer, tick what comes with you, then start the migration. This computer is waiting.",
  "Installation des comptes et des applications": "Setting up accounts and apps",
  "Le nouvel ordinateur installe vos applications. Cela peut prendre plusieurs minutes ; l'envoi des fichiers suit.": "The new computer is installing your apps. This can take several minutes; your files will be sent next.",
  "Envoi en cours": "Sending",
  "Vous pouvez continuer à utiliser cet ordinateur, mais évitez de modifier des fichiers.": "You can keep using this computer, but try not to change any files.",
  "Derniers réglages": "Final settings",
  "Le nouvel ordinateur applique vos réglages. C'est presque fini.": "The new computer is applying your settings. Almost done.",
  "Code à 6 chiffres": "6-digit code",
  "Chiffre {0}": "Digit {0}",
  "Bienvenue dans Bernard": "Welcome to Bernard",
  "Bernard déménage vos comptes, vos documents, vos réglages et vos applications d'un ordinateur à l'autre. Ouvrez-le sur les deux ordinateurs, dans l'ordre que vous voulez.": "Bernard moves your accounts, documents, settings and apps from one computer to another. Open it on both computers, in whichever order you like.",
  "Ceci est le nouvel ordinateur": "This is the new computer",
  "Recevoir les données d'un ancien ordinateur ou d'un disque externe.": "Receive data from an old computer or an external drive.",
  "Ceci est l'ancien ordinateur": "This is the old computer",
  "Envoyer ses données vers le nouvel ordinateur, ou les préparer sur un disque externe. Rien n'y est modifié.": "Send its data to the new computer, or prepare it on an external drive. Nothing on it is changed.",
  "Transférer depuis cet ordinateur": "Transfer from this computer",
  "Comment voulez-vous transmettre vos données au nouvel ordinateur ?": "How would you like to send your data to the new computer?",
  "Directement au nouvel ordinateur": "Straight to the new computer",
  "Par le Wi-Fi ou un câble réseau. Les deux ordinateurs doivent être allumés ; le nouveau peut être encore en cours d'installation, cet ordinateur l'attendra.": "Over Wi-Fi or a network cable. Both computers need to be switched on; the new one can still be installing, this computer will wait for it.",
  "Sur un disque externe": "To an external drive",
  "Un paquet chiffré, à brancher ensuite sur le nouvel ordinateur. Utile sans réseau commun.": "An encrypted package you then plug into the new computer. Handy when there is no shared network.",
  "En attente du nouvel ordinateur": "Waiting for the new computer",
  "Sur le nouvel ordinateur, ouvrez Bernard, choisissez « Ceci est le nouvel ordinateur » puis « Depuis un autre ordinateur ». Il apparaîtra ici tout seul.": "On the new computer, open Bernard, choose “This is the new computer” then “From another computer”. It will show up here on its own.",
  "Recherche sur le Wi-Fi et les câbles réseau…": "Searching over Wi-Fi and network cables…",
  "Le nouvel ordinateur est encore en cours d'installation ? Aucun problème : cet ordinateur l'attend aussi longtemps qu'il le faut, sans charger le réseau, et ne se mettra pas en veille.": "Is the new computer still being installed? No problem: this computer will wait as long as it takes, without loading the network, and won't go to sleep.",
  "Toujours rien ? Vérifiez que les deux ordinateurs sont sur le même réseau. Certains Wi-Fi (invités, entreprise) empêchent les appareils de se voir : reliez-les alors par un câble réseau.": "Still nothing? Check that both computers are on the same network. Some Wi-Fi networks (guest, office) stop devices from seeing each other: in that case, connect them with a network cable.",
  "Annuler": "Cancel",
  "Nouvel ordinateur trouvé": "New computer found",
  "Saisissez le code à 6 chiffres affiché sur le nouvel ordinateur.": "Enter the 6-digit code shown on the new computer.",
  "Connexion…": "Connecting…",
  "Envoyé": "Sent",
  "Débit": "Speed",
  "Reste environ": "Time left",
  "Liaison": "Connection",
  "Pour aller plus vite, branchez un câble réseau entre les deux ordinateurs (ou vers la box) : Bernard basculera dessus tout seul, sans rien interrompre.": "To go faster, plug a network cable between the two computers (or into the router): Bernard will switch to it on its own, without interrupting anything.",
  "Journal détaillé": "Detailed log",
  "Une coupure n'est pas grave : l'envoi reprend là où il s'était arrêté.": "A break in the connection is no problem: sending picks up where it left off.",
  "Arrêter": "Stop",
  "Arrêter l'envoi ?": "Stop sending?",
  "Ce qui est déjà arrivé et vérifié sur le nouvel ordinateur est conservé.": "Whatever has already arrived and been checked on the new computer is kept.",
  "Préparer un disque externe": "Prepare an external drive",
  "Bernard y écrit un paquet chiffré avec vos comptes, documents, réglages et la liste de vos applications.": "Bernard writes an encrypted package to it with your accounts, documents, settings and the list of your apps.",
  "{0} libres": "{0} free",
  "Aucun disque externe détecté. Branchez un disque ou une clé USB, puis <button class=\"link\" data-act=\"refresh\">cherchez à nouveau</button>.": "No external drive found. Plug in a drive or a USB stick, then <button class=\"link\" data-act=\"refresh\">search again</button>.",
  "Il faut environ {0} d'espace libre.": "About {0} of free space is needed.",
  "Inventaire de cet ordinateur en cours…": "Taking stock of this computer…",
  "Phrase de passe (8 caractères au moins)": "Passphrase (at least 8 characters)",
  "Confirmation": "Confirm",
  "Notez-la : elle sera demandée sur le nouvel ordinateur, et personne ne peut ouvrir le paquet sans elle.": "Write it down: the new computer will ask for it, and nobody can open the package without it.",
  "Écrire le paquet": "Write the package",
  "La phrase de passe doit faire au moins 8 caractères.": "The passphrase must be at least 8 characters long.",
  "Les deux phrases de passe diffèrent.": "The two passphrases don't match.",
  "Le paquet est prêt": "The package is ready",
  "{0} ({1}), chiffrés.": "{0} ({1}), encrypted.",
  "Éjectez le disque, puis branchez-le sur le nouvel ordinateur.": "Eject the drive, then plug it into the new computer.",
  "Ouvrez Bernard sur le nouvel ordinateur : « Ceci est le nouvel ordinateur », puis « Depuis un disque externe ».": "Open Bernard on the new computer: “This is the new computer”, then “From an external drive”.",
  "Saisissez la phrase de passe choisie ici.": "Enter the passphrase you chose here.",
  "Dossier : {0}": "Folder: {0}",
  "{0} éléments non inclus": "{0} items not included",
  "Transfert terminé": "Transfer complete",
  "Vos données sont arrivées sur {0}, et chaque fichier y a été vérifié. Rien n'a été modifié sur cet ordinateur.": "Your data has arrived on {0}, and every file there has been checked. Nothing has been changed on this computer.",
  "le nouvel ordinateur": "the new computer",
  "Gardez cet ordinateur tel quel tant que vous n'avez pas tout vérifié sur le nouveau.": "Keep this computer as it is until you have checked everything on the new one.",
  "Fermer Bernard": "Close Bernard",
  "Envoi interrompu": "Sending interrupted",
  "Ce qui est déjà arrivé et vérifié sur le nouvel ordinateur ne sera pas renvoyé.": "Whatever has already arrived and been checked on the new computer won't be sent again.",
  "Pour reprendre, cliquez sur « Reprendre » : Bernard retrouvera le nouvel ordinateur, qui affiche un nouveau code. Si Bernard y a été fermé entre-temps, rouvrez-le d'abord (« Depuis un autre ordinateur »). La migration continuera là où elle s'était arrêtée.": "To carry on, click “Resume”: Bernard will find the new computer again, which shows a new code. If Bernard was closed there in the meantime, open it again first (“From another computer”). The migration will pick up where it left off.",
  "Reprendre": "Resume",
  "Transférer vers cet ordinateur": "Transfer to this computer",
  "Bernard installe ici vos comptes, vos documents, vos réglages et vos applications, en les reprenant de votre ancien ordinateur.": "Bernard sets up your accounts, documents, settings and apps here, bringing them over from your old computer.",
  "Depuis un autre ordinateur": "From another computer",
  "Par le Wi-Fi, un câble réseau ou un câble Thunderbolt. Les deux ordinateurs doivent être allumés.": "Over Wi-Fi, a network cable or a Thunderbolt cable. Both computers need to be switched on.",
  "Depuis un disque externe": "From an external drive",
  "Vous avez déjà préparé un paquet Bernard sur un disque ou une clé USB.": "You have already prepared a Bernard package on a drive or USB stick.",
  "Reliez l'ancien ordinateur": "Connect the old computer",
  "Les deux ordinateurs doivent être sur le même réseau, ou reliés par un câble.": "Both computers need to be on the same network, or connected by a cable.",
  "Sur l'ancien ordinateur, ouvrez Bernard et choisissez « Ceci est l'ancien ordinateur », puis « Directement au nouvel ordinateur ».": "On the old computer, open Bernard and choose “This is the old computer”, then “Straight to the new computer”.",
  "Il trouvera cet ordinateur tout seul et vous demandera ce code :": "It will find this computer on its own and ask you for this code:",
  "Code d'appairage {0}": "Pairing code {0}",
  "En attente de l'ancien ordinateur…": "Waiting for the old computer…",
  "Un câble réseau est plus rapide que le Wi-Fi. Un câble USB-C ne fonctionne que si les deux ordinateurs ont un port Thunderbolt ou USB4. Vous pourrez changer de liaison pendant le transfert.": "A network cable is faster than Wi-Fi. A USB-C cable only works if both computers have a Thunderbolt or USB4 port. You can switch connections during the transfer.",
  "La recherche automatique ne trouve pas cet ordinateur ?": "The automatic search can't find this computer?",
  "Certains Wi-Fi (invités, entreprise) empêchent les appareils de se voir. Reliez les deux ordinateurs par un câble. En dernier recours, dans un terminal sur l'ancien ordinateur :": "Some Wi-Fi networks (guest, office) stop devices from seeing each other. Connect the two computers with a cable. As a last resort, in a terminal on the old computer:",
  "Aucune adresse réseau active.": "No active network address.",
  "Ouvrir le paquet de migration": "Open the migration package",
  "Branchez le disque qui contient le paquet préparé sur l'ancien ordinateur.": "Plug in the drive holding the package prepared on the old computer.",
  "Paquet": "Package",
  "Aucun paquet trouvé automatiquement : indiquez son dossier.": "No package found automatically: enter its folder.",
  "Phrase de passe du paquet": "Package passphrase",
  "Ouvrir le paquet": "Open the package",
  "Analyse de l'ancien ordinateur": "Looking at the old computer",
  "Connecté à {0}.": "Connected to {0}.",
  "Bernard fait l'inventaire des comptes, des applications et des dossiers. Rien n'est encore copié.": "Bernard is taking stock of the accounts, apps and folders. Nothing has been copied yet.",
  "Lecture en cours…": "Reading…",
  "Choisissez ce qui vient avec vous": "Choose what comes with you",
  "Depuis {0} ({1}).": "From {0} ({1}).",
  "l'ancien ordinateur": "the old computer",
  "Tout est coché par défaut, sauf les applications que vous n'utilisez plus depuis plus d'un an.": "Everything is ticked by default, except apps you haven't used for over a year.",
  "Comptes": "Accounts",
  "Dossiers personnels": "Home folders",
  "Dossier personnel de {0}": "Home folder of {0}",
  "{0}, {1}. Les caches et la corbeille ne sont pas copiés.": "{0}, {1}. Caches and the bin are not copied.",
  "Réglages": "Settings",
  "Réglages de {0}": "Settings of {0}",
  "Traduits": "Adapted",
  "Partiel": "Partial",
  "Identiques": "Identical",
  "Ne plus ouvrir seule la session « {0} »": "Stop signing in to “{0}” automatically",
  "Au démarrage, cet ordinateur ouvre directement le compte {0}. Après la migration, l'écran de connexion vous laissera choisir votre compte.": "At start-up, this computer goes straight into the {0} account. After the migration, the login screen will let you choose your account.",
  "Applications": "Apps",
  "Tout sélectionner": "Select all",
  "Dépôt de logiciels {0}": "Software source {0}",
  "Ajouté ici pour réinstaller les logiciels qui en viennent. S'il ne répond pas pour cette version du système, il est retiré aussitôt.": "Added here to reinstall the software that comes from it. If it doesn't respond for this version of the system, it is removed straight away.",
  "Dépôt": "Source",
  "Aucune application à installer : tout est déjà présent.": "No apps to install: everything is already here.",
  "Afficher les {0} éléments déjà présents sur cet ordinateur": "Show the {0} items already on this computer",
  "Tout ne tient pas sur ce disque : {0} hors des dossiers personnels ont été décochés ({1}).": "Not everything fits on this disk: {0} outside the home folders have been unticked ({1}).",
  "Tout ne tient pas sur ce disque : {0} hors des dossiers personnels a été décoché ({1}).": "Not everything fits on this disk: {0} outside the home folders has been unticked ({1}).",
  "Vos dossiers personnels passent en priorité ; ajustez ci-dessous ce que vous voulez emporter.": "Your home folders come first; adjust below what you want to bring.",
  "Réseau et imprimantes": "Network and printers",
  "Wi-Fi « {0} »": "Wi-Fi “{0}”",
  "Le mot de passe du réseau est repris.": "The network password comes along.",
  "VPN « {0} »": "VPN “{0}”",
  "Réglages repris, module VPN installé au besoin. Un mot de passe demandé à chaque connexion restera à saisir.": "Settings come along, and the VPN add-on is installed if needed. A password asked for at each connection will still need to be typed.",
  "Imprimante {0}": "Printer {0}",
  "Réinstallée automatiquement si c'est une imprimante réseau ; une imprimante USB sera à rebrancher.": "Set up again automatically if it is a network printer; a USB printer will need plugging in again.",
  "Lancer la migration": "Start the migration",
  "Masquer les éléments déjà présents": "Hide the items already here",
  "Annuler la migration ?": "Undo the migration?",
  "Rien n'a encore été modifié. Vous reviendrez à l'accueil.": "Nothing has been changed yet. You will go back to the start.",
  "Annuler la migration": "Undo the migration",
  "Migration en cours": "Migration in progress",
  "Vous pouvez utiliser les deux ordinateurs, mais évitez de modifier des fichiers sur l'ancien. Chaque fichier est vérifié avant d'être rangé.": "You can use both computers, but try not to change files on the old one. Every file is checked before it is put in place.",
  "Étape": "Step",
  "Copié": "Copied",
  "Une coupure n'est pas grave : le transfert reprend là où il s'était arrêté.": "A break in the connection is no problem: the transfer picks up where it left off.",
  "Arrêter la migration ?": "Stop the migration?",
  "Ce qui est déjà copié et vérifié est conservé. Pour reprendre, relancez Bernard sur les deux ordinateurs.": "Whatever has already been copied and checked is kept. To carry on, open Bernard again on both computers.",
  "Migration annulée": "Migration undone",
  "Tout est arrivé": "Everything arrived",
  "Migration terminée, quelques éléments à revoir": "Migration finished, a few things to look at",
  "Cet ordinateur est revenu à son état d'avant la migration, à l'exception des fichiers modifiés depuis. Voici ce qui avait été fait.": "This computer is back to how it was before the migration, apart from files changed since. Here is what had been done.",
  "Chaque fichier a été vérifié. Redémarrez l'ordinateur avant d'utiliser vos applications : mots de passe des navigateurs et réglages du bureau ne sont pris en compte qu'à la prochaine ouverture de session.": "Every file has been checked. Restart the computer before using your apps: browser passwords and desktop settings only take effect the next time you sign in.",
  "Tout le reste a été copié et vérifié. Voici ce qui demande votre attention.": "Everything else has been copied and checked. Here is what needs your attention.",
  "{0} ({1} copiés pendant cette migration)": "{0} ({1} copied during this migration)",
  "Compte {0} créé": "Account {0} created",
  "Retirées, comme sur l'ancien ordinateur : {0}": "Removed, as on the old computer: {0}",
  "Trousseau de clés et profils des navigateurs de l'ancien ordinateur mis en place (ceux d'ici sont gardés dans ~/.local/share/bernard/avant-migration)": "Keyring and browser profiles from the old computer put in place (the ones from here are kept in ~/.local/share/bernard/avant-migration)",
  "{0} : échec ({1})": "{0}: failed ({1})",
  "{0} : {1}": "{0}: {1}",
  "À faire à la main": "To do by hand",
  "Fichiers renommés": "Renamed files",
  "Un fichier du même nom existait déjà ici ; il a été conservé et la copie a reçu un nouveau nom.": "A file with the same name was already here; it has been kept and the copy was given a new name.",
  "{0} fichiers spéciaux ignorés (tubes, sockets)": "{0} special files skipped (pipes, sockets)",
  "Ce bilan est aussi rangé dans vos documents : {0}.": "This summary is also saved in your documents: {0}.",
  "Il contient une liste de vérifications à faire tranquillement.": "It includes a list of checks to go through at your own pace.",
  "Rapport détaillé : {0}": "Detailed report: {0}",
  "Gardez l'ancien ordinateur intact pour l'instant.": "Keep the old computer as it is for now.",
  "Imprimer le bilan": "Print the summary",
  "Fermer": "Close",
  "Redémarrer maintenant": "Restart now",
  "aucun fichier personnel": "no personal files",
  "Supprimer le compte « {0} » ?": "Delete the account “{0}”?",
  "Au prochain démarrage, avant l'écran de connexion, le compte {0} et son dossier personnel seront supprimés ({1}). Cette suppression est définitive. Vous pouvez encore changer d'avis ici tant que l'ordinateur n'a pas redémarré.": "At the next start-up, before the login screen, the account {0} and its home folder will be deleted ({1}). This cannot be undone. You can still change your mind here until the computer restarts.",
  "Supprimer au prochain démarrage": "Delete at next start-up",
  "Redémarrer maintenant ?": "Restart now?",
  "Fermez d'abord vos autres applications. Après le redémarrage, connectez-vous avec votre compte : tout sera en place.": "Close your other apps first. After the restart, sign in with your account: everything will be in place.",
  "Redémarrer": "Restart",
  "Bernard retirera les fichiers qu'il a copiés (sauf ceux modifiés depuis), les applications et les comptes qu'il a ajoutés. Les fichiers qui étaient déjà sur cet ordinateur ne sont pas touchés.": "Bernard will remove the files it copied (except those changed since), and the apps and accounts it added. Files that were already on this computer are left alone.",
  "Migration interrompue": "Migration interrupted",
  "Ce qui a été copié et vérifié est conservé. Rien ne sera recopié.": "Whatever has been copied and checked is kept. Nothing will be copied twice.",
  "Pour reprendre : fermez Bernard, relancez-le ici (« Depuis un autre ordinateur »), puis sur l'ancien ordinateur cliquez sur « Reprendre ». La migration continuera là où elle s'était arrêtée.": "To carry on: close Bernard, open it again here (“From another computer”), then on the old computer click “Resume”. The migration will pick up where it left off.",
  "De {0} vers {1}, les réglages du bureau ne se transposent pas. Les tâches planifiées suivent.": "Desktop settings can't be carried over from {0} to {1}. Scheduled tasks come along.",
  "Bureau non reconnu : les réglages du bureau ne sont pas repris. Les tâches planifiées suivent.": "Desktop not recognised: desktop settings are not carried over. Scheduled tasks come along.",
  "Traduits de {0} vers {1} : fond d'écran, clavier, souris, favoris, taille du texte, veille. Tâches planifiées incluses.": "Adapted from {0} to {1}: wallpaper, keyboard, mouse, favourites, text size, sleep. Scheduled tasks included.",
  "Fond d'écran, souris, dock, polices, veille, terminal. Tâches planifiées incluses. La disposition du clavier d'ici est conservée.": "Wallpaper, mouse, dock, fonts, sleep, terminal. Scheduled tasks included. The keyboard layout here is kept.",
  "Fond d'écran, clavier, souris, dock, polices, veille, terminal. Tâches planifiées incluses.": "Wallpaper, keyboard, mouse, dock, fonts, sleep, terminal. Scheduled tasks included.",
  "composant technique, inutile ici": "technical component, not needed here",
  "lié au matériel de l'ancien ordinateur : chaque ordinateur garde ses propres pilotes": "tied to the old computer's hardware: each computer keeps its own drivers",
  "déjà installé": "already installed",
  "autre": "other",
  "inconnue": "unknown",
  "Vous l'aviez retirée de l'ancien ordinateur le {0}.": "You removed it from the old computer on {0}.",
  "Absente de l'ancien ordinateur.": "Not on the old computer.",
  "Absente de l'ancien ordinateur, dont le système est d'une autre version : elle est peut-être simplement nouvelle ici.": "Not on the old computer, which runs a different system version: it may simply be new here.",
  "Libère {0}.": "Frees {0}.",
  "Retire aussi : {0}.": "Also removes: {0}.",
  "Applications absentes de l'ancien ordinateur": "Apps not on the old computer",
  "Installées d'office avec {0}, mais que vous n'avez pas sur l'ancien ordinateur.": "Installed as standard with {0}, but not on your old computer.",
  "ce système": "this system",
  "Cochées : elles seront retirées d'ici. Vos fichiers ne sont pas touchés, et « Annuler la migration » les réinstalle.": "Ticked ones will be removed from here. Your files are not touched, and “Undo the migration” reinstalls them.",
  "Tout cocher": "Tick all",
  "Clavier": "Keyboard",
  "Le clavier de cet ordinateur ({0}) n'est pas celui de l'ancien ({1}).": "This computer's keyboard ({0}) is not the same as the old one's ({1}).",
  "inconnu": "unknown",
  "La disposition choisie à l'installation est conservée. Cochez seulement si vous utiliserez ici le même clavier qu'avant.": "The layout chosen during installation is kept. Only tick this if you will use the same keyboard here as before.",
  "Reprendre la disposition de l'ancien ordinateur pour {0}": "Use the old computer's layout for {0}",
  "Disposition {0} au lieu de {1}.": "Layout {0} instead of {1}.",
  "celle d'ici": "the one here",
  "Matériel": "Hardware",
  "Carte graphique ici : {0} ; sur l'ancien : {1}.": "Graphics card here: {0}; on the old one: {1}.",
  "Pilotes, micrologiciels et noyau ne sont jamais recopiés ni retirés : chaque ordinateur garde ceux choisis pour lui.": "Drivers, firmware and kernel are never copied or removed: each computer keeps the ones chosen for it.",
  "Les caches graphiques des navigateurs ne sont pas copiés, ils se refont seuls.": "Browser graphics caches are not copied; they rebuild themselves.",
  "Options avancées": "Advanced options",
  "Dernière utilisation : {0}, {1}": "Last used: {0}, {1}",
  "Date de dernière utilisation inconnue": "Last used: unknown",
  "introuvable dans les dépôts de cet ordinateur": "not found in this computer's software sources",
  "pas d'équivalent automatique": "no automatic equivalent",
  "suggestion : {0}": "suggestion: {0}",
  "Équivalent Flathub": "Flathub equivalent",
  "Identique": "Identical",
  "Compte {0}": "Account {0}",
  "Ce compte existe déjà ici : les fichiers y seront ajoutés, sans rien écraser.": "This account already exists here: files will be added to it without overwriting anything.",
  "Nouveau compte. Choisissez son mot de passe.": "New account. Choose its password.",
  "Nouveau compte, avec le même mot de passe qu'avant.": "New account, with the same password as before.",
  "Mot de passe": "Password",
  "{0} d'ici ({1} libérés).": "{0} from here ({1} freed).",
  "{0} d'ici.": "{0} from here.",
  "Voir et choisir": "See and choose",
  "Aucune application ne sera retirée d'ici.": "No apps will be removed from here.",
  "Voir les propositions": "See the suggestions",
  "À copier : {0} sur {1} libres.": "To copy: {0} of {1} free.",
  "{0} à installer.": "{0} to install.",
  "Aucune application à installer.": "No apps to install.",
  "Choisissez un mot de passe pour le compte {0}.": "Choose a password for the account {0}.",
  "Les deux mots de passe du compte {0} diffèrent.": "The two passwords for the account {0} don't match.",
  "Comptes et applications": "Accounts and apps",
  "Copie des fichiers": "Copying files",
  "en pause": "paused",
  "mesure…": "measuring…",
  "Liaison perdue. Bernard attend l'ancien ordinateur par une autre liaison (câble ou Wi-Fi) ; le transfert reprendra seul.": "Connection lost. Bernard is waiting for the old computer over another connection (cable or Wi-Fi); the transfer will resume on its own.",
  "Si l'envoi a été arrêté sur l'ancien ordinateur, cliquez-y sur « Reprendre » et saisissez ce code :": "If sending was stopped on the old computer, click “Resume” there and enter this code:",
  "En attente depuis {0}…": "Waiting for {0}…",
  "Plusieurs nouveaux ordinateurs sont visibles : choisissez le vôtre.": "Several new computers are visible: choose yours.",
  "par {0}": "via {0}",
  "Cet ordinateur : {0}, {1}, {2} de données.": "This computer: {0}, {1}, {2} of data.",
  "Écriture du paquet": "Writing the package",
  "Vous pouvez continuer à utiliser cet ordinateur. Ne débranchez pas le disque.": "You can keep using this computer. Don't unplug the drive.",
  "Installation sur le nouvel ordinateur…": "Installing on the new computer…",
  "Patientez…": "Please wait…",
  "Liaison perdue. Bernard cherche le nouvel ordinateur par une autre liaison (câble ou Wi-Fi) ; l'envoi reprendra seul.": "Connection lost. Bernard is looking for the new computer over another connection (cable or Wi-Fi); sending will resume on its own.",
  "Sites web": "Websites",
  "Base de données": "Database",
  "Conteneurs": "Containers",
  "Machines virtuelles": "Virtual machines",
  "Serveur": "Server",
  "Logiciel": "Software",
  "Service": "Service",
  "Programmes": "Programs",
  "Réglages système": "System settings",
  "Administrateur": "Administrator",
  "Dossier": "Folder",
  "Disque": "Disk",
  "Dossier personnel": "Home folder",
  "Sauvegarde": "Backup",
  "Jeux": "Games",
  "À reprendre.": "Worth bringing.",
  "Sauvegarde : inutile de la copier si les données qu'elle protège sont déjà migrées.": "Backup: no need to copy it if the data it protects is already being migrated.",
  "Autre disque : à brancher tel quel dans le nouvel ordinateur, ou à copier.": "Another disk: fit it as it is in the new computer, or copy it.",
  "À examiner : Bernard ne sait pas si c'est utile.": "Worth a look: Bernard can't tell whether it is useful.",
  "({0} réellement occupés : fichiers creux)": "({0} actually used: sparse files)",
  "Choix de l'emplacement sur le nouvel ordinateur : prochaine version.": "Choosing where it goes on the new computer: coming in the next version.",
  "Données": "Data",
  "Hors des dossiers personnels": "Outside the home folders",
  "Bernard a examiné tout le disque de l'ancien ordinateur. Voici ce qui n'appartient ni au système ni à vos dossiers personnels (environ {0} hors sauvegardes).": "Bernard has looked through the whole disk of the old computer. Here is what belongs neither to the system nor to your home folders (about {0}, not counting backups).",
  "Bernard a examiné tout le disque de l'ancien ordinateur. Voici ce qui n'appartient ni au système ni à vos dossiers personnels.": "Bernard has looked through the whole disk of the old computer. Here is what belongs neither to the system nor to your home folders.",
  "Chaque élément est copié au même endroit, avec ses propriétaires et ses droits ; un fichier déjà présent ici est mis de côté, et « Annuler la migration » le remet en place.": "Each item is copied to the same place, with its owners and permissions; a file already here is set aside, and “Undo the migration” puts it back.",
  "votre compte « {0} »": "your account “{0}”",
  "votre compte": "your account",
  "Compte provisoire": "Temporary account",
  "Ce compte ne vient pas de l'ancien ordinateur : sans doute celui créé pour installer le système. Au redémarrage, choisissez {0} sur l'écran de connexion. Si vous êtes sûr de votre coup, le compte provisoire peut être supprimé au redémarrage ; sinon, gardez-le et supprimez-le plus tard depuis Paramètres → Utilisateurs.": "This account doesn't come from the old computer: it is probably the one created to install the system. When you restart, choose {0} on the login screen. If you are sure, the temporary account can be deleted at restart; otherwise, keep it and delete it later from Settings → Users.",
  "(session ouverte en ce moment)": "(signed in right now)",
  "Aucun fichier personnel": "No personal files",
  "administrateur": "administrator",
  "Sera supprimé au prochain démarrage.": "Will be deleted at the next start-up.",
  "Garder ce compte": "Keep this account",
  "Resté sur l'ancien ordinateur": "Left on the old computer",
  "Ces éléments hors des dossiers personnels n'ont pas été copiés (non cochés, ou copie prévue dans une prochaine version). Gardez l'ancien ordinateur tant qu'ils ne sont pas repris.": "These items outside the home folders were not copied (not ticked, or copying planned for a later version). Keep the old computer until they have been brought over.",
  "comptes supprimés : {0}": "accounts deleted: {0}",
  "Migration annulée.": "Migration undone.",
  "{0} depuis la copie conservé(s).": "{0} since the copy, left untouched.",
  "Non annulé : {0}": "Not undone: {0}",
  "Bernard s'est arrêté": "Bernard has stopped",
  "Vous pouvez fermer cette fenêtre.": "You can close this window.",
  "fichier écrit": "file written",
  "fichiers écrits": "files written",
  "fichier envoyé": "file sent",
  "fichiers envoyés": "files sent",
  "fichier": "file",
  "fichiers": "files",
  "élément": "item",
  "éléments": "items",
  "fichier vérifié": "file checked",
  "fichiers vérifiés": "files checked",
  "application installée": "app installed",
  "applications installées": "apps installed",
  "fichier personnel": "personal file",
  "fichiers personnels": "personal files",
  "application que vous n'avez pas sur l'ancien ordinateur sera retirée": "app you don't have on the old computer will be removed",
  "applications que vous n'avez pas sur l'ancien ordinateur seront retirées": "apps you don't have on the old computer will be removed",
  "application": "app",
  "applications": "apps",
  "compte": "account",
  "comptes": "accounts",
  "fichier retiré": "file removed",
  "fichiers retirés": "files removed",
  "application retirée": "app removed",
  "applications retirées": "apps removed",
  "application réinstallée": "app reinstalled",
  "applications réinstallées": "apps reinstalled",
  "fichier modifié": "file changed",
  "fichiers modifiés": "files changed"
};
