#!/bin/bash
# Test de bout en bout RÉEL, en administrateur, sur une machine jetable
# (machine virtuelle, conteneur, exécuteur d'intégration continue).
#
# Il crée un faux système source (comptes, mots de passe, fichiers, Wi-Fi,
# tâches planifiées), migre vers la machine courante avec les vrais binaires,
# vérifie le résultat, puis annule et vérifie que tout a été retiré.
#
#   sudo tests/e2e/run.sh [dossier-des-binaires]
#
# NE PAS lancer sur un poste de travail : il crée et supprime des comptes.
set -u
BIN=${1:-bin}
SRC=$(mktemp -d /tmp/bernard-e2e-src.XXXX)
LOG=$(mktemp /tmp/bernard-e2e-log.XXXX)
PORT=51599
FAILS=0
ok()   { echo "  ok    $*"; }
bad()  { echo "  ÉCHEC $*"; FAILS=$((FAILS+1)); }
check(){ local what=$1; shift; if "$@" >/dev/null 2>&1; then ok "$what"; else bad "$what"; fi; }

[ "$(id -u)" -eq 0 ] || { echo "Lancez avec sudo."; exit 2; }
for u in e2ealice e2ebob; do
  getent passwd $u >/dev/null && { echo "Le compte $u existe déjà : machine non vierge, arrêt."; exit 2; }
done

echo "== Préparation du faux système source"
HASH='$6$bernardsel$Wm3TQ0bYhYpwDDz3MuDO0M8sM0VNeeL9HCo1ZbFRtR3m3y2Xb0mBv0TtTnB0GmxvZ/3hLgE0dRPm0ydsK2A8/.'
mkdir -p $SRC/etc/NetworkManager/system-connections $SRC/var/spool/cron/crontabs
printf 'ID=ubuntu\nVERSION_ID="24.04"\n' > $SRC/etc/os-release
printf 'root:x:0:0::/root:/bin/bash\ne2ealice:x:1601:1601:Alice E2E,,,:/home/e2ealice:/bin/bash\ne2ebob:x:1602:1602:Bob,,,:/home/e2ebob:/bin/bash\n' > $SRC/etc/passwd
printf 'sudo:x:27:e2ealice\naudio:x:29:e2ealice,e2ebob\n' > $SRC/etc/group
printf 'e2ealice:%s:19000:0:99999:7:::\ne2ebob:!:19000:0:99999:7:::\n' "$HASH" > $SRC/etc/shadow
mkdir -p $SRC/home/e2ealice/{Documents,Images,.cache,.ssh} $SRC/home/e2ebob
echo "lettre" > "$SRC/home/e2ealice/Documents/lettre été.odt"
head -c 50000000 /dev/urandom > $SRC/home/e2ealice/Images/album.tar
echo "alias ll='ls -l'  # bashrc de l'ancien PC" > $SRC/home/e2ealice/.bashrc
echo "clé" > $SRC/home/e2ealice/.ssh/id_ed25519 && chmod 600 $SRC/home/e2ealice/.ssh/id_ed25519
echo "jetable" > $SRC/home/e2ealice/.cache/x
echo "notes" > $SRC/home/e2ebob/notes.txt
ln -s Documents $SRC/home/e2ealice/docs
printf '# DO NOT EDIT THIS FILE\n0 3 * * * echo sauvegarde\n' > $SRC/var/spool/cron/crontabs/e2ealice
cat > $SRC/etc/NetworkManager/system-connections/Maison.nmconnection <<'NM'
[connection]
id=E2E-Maison
uuid=0b5b7a3e-9f2a-4a38-9d6e-2f3c1a7b8e99
type=wifi
interface-name=wlp9s0

[wifi]
ssid=E2E-Maison

[wifi-security]
key-mgmt=wpa-psk
psk=secret-e2e
NM
# 0.7 : connexion VPN WireGuard et fichier à deux noms (lien dur).
cat > $SRC/etc/NetworkManager/system-connections/wg.nmconnection <<'NM'
[connection]
id=E2E-VPN
uuid=0b5b7a3e-9f2a-4a38-9d6e-2f3c1a7b8e98
type=wireguard
interface-name=wge2e

[wireguard]
private-key=cle-privee-e2e
NM
mkdir -p $SRC/home/e2ealice/Sauvegarde
ln $SRC/home/e2ealice/Images/album.tar $SRC/home/e2ealice/Sauvegarde/album.tar
# Données hors des dossiers personnels (0.5) : logiciel dans /opt (avec un
# fichier creux), site web appartenant à www-data, réglage ajouté dans /etc,
# réglage qui remplace celui de la cible, dossier ajouté à la racine.
mkdir -p $SRC/opt/e2eappli/bin $SRC/var/www/html/e2esite $SRC/data/e2eprojets
printf '#!/bin/sh\necho outil\n' > $SRC/opt/e2eappli/bin/outil && chmod 755 $SRC/opt/e2eappli/bin/outil
truncate -s 200M $SRC/opt/e2eappli/disque.img && echo "données" | dd of=$SRC/opt/e2eappli/disque.img bs=1 seek=100000000 conv=notrunc 2>/dev/null
echo "<?php echo 'e2e';" > $SRC/var/www/html/e2esite/index.php && chown -R 33:33 $SRC/var/www/html/e2esite
echo "reglage=e2e" > $SRC/etc/e2e-appli.conf
echo "version de l'ancien PC" > $SRC/etc/e2e-remplace.conf
echo "version du nouveau PC" > /etc/e2e-remplace.conf
echo "plan" > $SRC/data/e2eprojets/plan.txt
# Couche overlay façon Docker (0.6) : fichier « effacé » et dossier opaque
# (attribut étendu), plus une ACL sur un fichier de /opt.
mkdir -p $SRC/var/lib/docker/overlay2/c1/diff/opaque
mknod $SRC/var/lib/docker/overlay2/c1/diff/efface c 0 0
python3 -c "import os; os.setxattr('$SRC/var/lib/docker/overlay2/c1/diff/opaque', 'trusted.overlay.opaque', b'y')"
echo "image" > $SRC/var/lib/docker/overlay2/c1/diff/fichier
python3 -c "import os; os.setxattr('$SRC/opt/e2eappli/bin/outil', 'user.bernard', b'attribut')"
BEFORE=$(find $SRC -type f -exec sha256sum {} + | sort | sha256sum)

echo "== Migration (nouveau mot de passe demandé pour e2ebob)"
coproc RECV { $BIN/bernard receive --system --yes --port $PORT 2>&1; }
RPID=$RECV_PID
exec 3<&${RECV[0]} 4>&${RECV[1]}
CODE=""
for _ in $(seq 1 50); do
  read -t 1 -r line <&3 || continue
  echo "$line" >> $LOG
  case "$line" in *"Code d'appairage"*) CODE=$(echo "$line" | sed 's/.*: //; s/ //g'); break;; esac
done
[ -n "$CODE" ] || { echo "Pas de code affiché"; cat $LOG; exit 1; }
# Mot de passe de e2ebob (compte verrouillé à la source) : saisi deux fois.
printf 'nouveau-mdp\nnouveau-mdp\n' >&4
$BIN/bernard-agent connect --root $SRC --target 127.0.0.1:$PORT --code $CODE > $LOG.agent 2>&1
wait $RPID 2>/dev/null
cat <&3 >> $LOG

echo "== Vérifications"
check "compte e2ealice créé avec son UID"        test "$(id -u e2ealice)" = 1601
check "mot de passe de e2ealice repris"           grep -qF "e2ealice:$HASH:" /etc/shadow
check "mot de passe de e2ebob défini"             bash -c "grep '^e2ebob:' /etc/shadow | cut -d: -f2 | grep -q '^\\$'"
check "groupe sudo repris"                        bash -c "id -nG e2ealice | grep -qw sudo"
check "document copié à l'identique"             cmp "$SRC/home/e2ealice/Documents/lettre été.odt" "/home/e2ealice/Documents/lettre été.odt"
check "gros fichier copié à l'identique"          cmp $SRC/home/e2ealice/Images/album.tar /home/e2ealice/Images/album.tar
check "propriétaire des fichiers"                 test "$(stat -c %U /home/e2ealice/Images/album.tar)" = e2ealice
check ".bashrc de l'ancien PC à la place du modèle" grep -q "ancien PC" /home/e2ealice/.bashrc
check "aucun .bashrc renommé en conflit"          bash -c "! ls /home/e2ealice | grep -q 'bernard 1'"
check "clé SSH en 600"                            test "$(stat -c %a /home/e2ealice/.ssh/id_ed25519)" = 600
check "lien symbolique recréé"                    test "$(readlink /home/e2ealice/docs)" = Documents
check "cache exclu"                               test ! -e /home/e2ealice/.cache/x
check "tâches planifiées reprises"                bash -c "crontab -u e2ealice -l | grep -q sauvegarde"
check "Wi-Fi repris en 600, sans nom d'interface" bash -c "f=\$(ls /etc/NetworkManager/system-connections/bernard-E2E-Maison*); test \$(stat -c %a \$f) = 600 && ! grep -q interface-name \$f && grep -q psk=secret-e2e \$f"
check "VPN WireGuard repris avec son interface"  bash -c "f=\$(ls /etc/NetworkManager/system-connections/bernard-E2E-VPN*); grep -q interface-name=wge2e \$f && grep -q cle-privee-e2e \$f"
check "lien dur recréé (même fichier)"           test "$(stat -c %i /home/e2ealice/Images/album.tar)" = "$(stat -c %i /home/e2ealice/Sauvegarde/album.tar)"
check "bilan lisible dans Documents"              bash -c "grep -q 'Bilan de la migration' '/home/e2ealice/Documents/Bilan de la migration (Bernard).html' && test \$(stat -c %U '/home/e2ealice/Documents/Bilan de la migration (Bernard).html') = e2ealice"
check "/opt : logiciel copié, exécutable"        test -x /opt/e2eappli/bin/outil
check "/opt : fichier creux resté creux"          bash -c "cmp $SRC/opt/e2eappli/disque.img /opt/e2eappli/disque.img && test \$(du -k /opt/e2eappli/disque.img | cut -f1) -lt 10240"
check "site web copié, propriétaire www-data"     test "$(stat -c %u /var/www/html/e2esite/index.php)" = 33
check "/etc : réglage ajouté"                     grep -q reglage=e2e /etc/e2e-appli.conf
check "/etc : réglage de l'ancien PC en place"    grep -q "ancien PC" /etc/e2e-remplace.conf
check "dossier /data copié"                       test -f /data/e2eprojets/plan.txt
check "Docker : fichier effacé d'overlay recréé"  test -c /var/lib/docker/overlay2/c1/diff/efface
check "Docker : dossier opaque (attribut étendu)" python3 -c "import os,sys; sys.exit(os.getxattr('/var/lib/docker/overlay2/c1/diff/opaque','trusted.overlay.opaque')!=b'y')"
check "attribut étendu d'un fichier de /opt"      python3 -c "import os,sys; sys.exit(os.getxattr('/opt/e2eappli/bin/outil','user.bernard')!=b'attribut')"
check "source strictement inchangée"             test "$(find $SRC -type f -exec sha256sum {} + | sort | sha256sum)" = "$BEFORE"

echo "== Annulation"
JOURNAL=$(ls /var/lib/bernard/*/journal.jsonl | head -1)
$BIN/bernard undo --journal "$JOURNAL" >> $LOG 2>&1
check "comptes supprimés"                         bash -c "! getent passwd e2ealice && ! getent passwd e2ebob"
check "fichiers copiés retirés"                   test ! -e /home/e2ealice/Images/album.tar
check "bilan retiré"                              test ! -e "/home/e2ealice/Documents/Bilan de la migration (Bernard).html"
check "Wi-Fi retiré"                              bash -c "! ls /etc/NetworkManager/system-connections/bernard-E2E* 2>/dev/null"
check "/opt : logiciel retiré"                    test ! -e /opt/e2eappli/bin/outil
check "/etc : réglage ajouté retiré"              test ! -e /etc/e2e-appli.conf
check "/etc : réglage du nouveau PC remis"        grep -q "nouveau PC" /etc/e2e-remplace.conf
check "dossier /data retiré"                      test ! -e /data/e2eprojets/plan.txt
check "Docker : données retirées"                 test ! -e /var/lib/docker/overlay2/c1/diff/fichier

# Nettoyage
rm -rf /home/e2ealice /home/e2ebob "$(dirname "$JOURNAL")" $SRC /opt/e2eappli /var/www/html/e2esite /data/e2eprojets
rm -f /etc/e2e-remplace.conf /etc/e2e-appli.conf
rm -rf /var/lib/docker/overlay2/c1
rmdir /data 2>/dev/null
crontab -u e2ealice -r 2>/dev/null
echo
if [ $FAILS -eq 0 ]; then echo "Test de bout en bout réussi."; rm -f $LOG $LOG.agent; exit 0; fi
echo "$FAILS vérification(s) en échec. Journal : $LOG (agent : $LOG.agent)"
exit 1
